# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f11b4c1768934850f2103801a07796be9f9d62f3570bd533fd9c6653b331d00a7ec6b7987a6b4feee98d93e084de30881d5281fe05ec4570f5e1f9b2a6c7300

test:
  secret_key_base: 8351d491137b495ea2bfe2fb03a1ed2f876095588ae257d1bdeb320eb6857604e146d75d666c66bd6c4417035c3038210b8310ff39d78e9a756cdc04d204c79f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
